### PR TITLE
Update header.html

### PR DESCRIPTION
**Pull request by tonejaco**
Fix link in header, missing "/Documentation

### CODE REVIEW

**Comment by parachvte** [comment]
Checkout https://github.com/Snapmaker/Documentation/blob/master/index.html

It should be `{{ '/gcode/G000-G001' | relative_url }}`, this will prepend the base URL.

Github Pages auto set `snapmaker.github.io/Documentation` as the base URL.

**Comment by parachvte** [comment]
Thanks for your help!

We've been too busy recently...I'm reading Marlin source code as well that I can help the refactor process.

**Comment by tonejaco** [comment]
Should I cancel this pull?

**Comment by parachvte** [comment]
Add commits to your branch, and push your origin, the PR will be updated as well.

**Comment by tonejaco** [comment]
I don't see that I can do a push from there. I did the pull from the master. Should have I done it from my branch? I created the branch after I did the pull here.

**Comment by parachvte** [comment]
Like I did, add commits to your branch and push to your remote.

Now we can safely merge it to master.

**Comment by tonejaco** [comment]
It looks to me that the change you made negated the need form my change.

**Pull request merged**
